---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bizilabi/lara10.getupdemo.xyz
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp -r .[^.]* $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev
    - cp .env.production .env
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan migrate --force
    - php artisan optimize
